# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LidarRealityKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LidarRealityKit

  target 'LidarRealityKitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LidarRealityKitUITests' do
    # Pods for testing
  end

end
